[package]
name = "infraction7/libphysicstween"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["PhysicsTween", "PhysicsTween/**", "wally.toml", "default.project.json", "LICENSE.md"]
exclude = ["**"]

[dependencies]
signal = "sleitnick/signal@2.0.1"